services:
  #micro sevise game 

networks:    
  pingpong.net:
    external: true

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8081:80"

    volumes:
      - /home/monabid/Desktop/ayoub1/spa/front:/var/www/html/
      - /home/monabid/Desktop/ayoub1/ft_trance_spa/pingpong/media:/var/www/html/media
      - /home/monabid/Desktop/ayoub1/nginx/conf.d:/etc/nginx/conf.d/
  
    networks:
      - pingpong.net

  redis:
    image: redis:7.2
    restart: always
    container_name: redis
    networks:
      - pingpong.net

