# Generated by Django 3.1 on 2024-05-27 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='login')),
                ('is_connected', models.BooleanField(default=False, verbose_name='is_connected')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('channel_id', models.CharField(max_length=255, null=True, verbose_name='socket')),
            ],
        ),
        migrations.CreateModel(
            name='InGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_date')),
                ('round', models.IntegerField(default=1, verbose_name='score')),
                ('game_started', models.BooleanField(default=False, verbose_name='score')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='online.player', to_field='login')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='online.player', to_field='login')),
            ],
        ),
    ]
