# Generated by Django 3.1 on 2024-05-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingame',
            name='player1',
            field=models.CharField(max_length=50, unique=True, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='ingame',
            name='player2',
            field=models.CharField(max_length=50, unique=True, verbose_name='login'),
        ),
    ]
