# Generated by Django 3.1 on 2024-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20240529_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='side',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
