# Generated by Django 3.1 on 2024-07-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_pongames'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='imageURL',
            field=models.CharField(default='None', max_length=500, verbose_name='imageURL'),
        ),
    ]
